backend:
  name: git-gateway

media_folder: "src/img/gallery" # Folder where user uploaded files should go

collections:
  - name: food
    label: "Food items"
    folder: "site/content/food"
    create: true
    fields:
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
      - {label: "Price", name: "price", widget: "string"}
  
  - name: drinks
    label: "Drink items"
    folder: "site/content/drinks"
    create: true
    field:
      - {label: "Name of Drink", name: "title", widget: "string"}
      - {label: "Drink Marker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Drink", name: "type", widget: "string", default: "beer"}
      - {label: "Price", name: "price", widget: "string"}